"""Lyrics search and line utilities on top of ``krok_helper.lyrics``.

A *line* (as stored in ``job.json → lyrics.lines``) is::

    {"text": "遠い記憶に", "ruby": [[0, 0, "とお"], [2, 3, "きおく", "auto"]],
     "t": 12.34 | None,          # reference time from a synced source (seconds)
     "tr": "translation" | None, "singer": "s1", "include": true}

Ruby spans are inclusive character ranges; a 4th element ``"auto"`` marks
readings generated by SUG's analyzer (shown dimmer in the page).
"""

from __future__ import annotations

import difflib
import re
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from typing import Any

from .paths import ensure_repo_on_path

_UTATEN_BLOCK = re.compile(r"\{([^{}|]+)\|\|([^{}]*)\}")
_META_LINE = re.compile(r"^\[(tool|ti|ar|al|by|offset|length|re|ve):", re.I)


def _service():
    ensure_repo_on_path()
    import krok_helper.network as net
    from krok_helper.lyrics import LyricsSearchService

    # Use the app's SSL context (system store + certifi) without its Qt settings.
    net.build_urllib_opener_for_current_settings = (
        lambda *handlers: urllib.request.build_opener(net.https_handler_for_shared_context(), *handlers)
    )
    return LyricsSearchService()


def parse_utaten_text(marked: str) -> list[dict]:
    lines = []
    for raw in marked.splitlines():
        raw = raw.strip()
        if not raw or _META_LINE.match(raw):
            continue
        text_parts: list[str] = []
        ruby: list[list[Any]] = []
        pos = 0
        cursor = 0
        for m in _UTATEN_BLOCK.finditer(raw):
            plain = raw[pos:m.start()]
            text_parts.append(plain)
            cursor += len(plain)
            base, reading = m.group(1), m.group(2)
            ruby.append([cursor, cursor + len(base) - 1, reading])
            text_parts.append(base)
            cursor += len(base)
            pos = m.end()
        text_parts.append(raw[pos:])
        text = "".join(text_parts)
        if text.strip():
            lines.append({"text": text, "ruby": ruby, "t": None, "tr": None})
    return lines


def parse_lrc_text(lrc: str) -> list[dict]:
    ensure_repo_on_path()
    from krok_helper.lyrics import parse_lrc_lines

    out = []
    for item in parse_lrc_lines(lrc):
        text = item.text.strip()
        if not text:
            continue
        out.append({"text": text, "ruby": [], "t": round(item.start_ms / 1000.0, 2), "tr": None})
    return out


_WORD_STAMP = re.compile(r"\[(\d+):(\d+(?:\.\d+)?)\]")


def parse_verbatim_text(lrc: str) -> list[dict]:
    """Word-level (逐字) LRC — ``[00:12.34]word[00:12.80]word …`` per line, as the
    engine builds it from NetEase YRC / Kugou KRC — into lines whose ``words``
    are ``[first_char, last_char, start_seconds]`` (inclusive, like ruby spans;
    ``_add_durations`` appends the word length when the raw source has it)."""
    out = []
    for raw in lrc.splitlines():
        stamps = list(_WORD_STAMP.finditer(raw))
        if not stamps:
            continue
        text, words = "", []
        for k, m in enumerate(stamps):
            piece = raw[m.end():stamps[k + 1].start() if k + 1 < len(stamps) else len(raw)]
            if not text:
                piece = piece.lstrip()
            core = piece.rstrip()
            if core.strip():
                first = len(text) + len(core) - len(core.lstrip())
                words.append([first, len(text) + len(core) - 1, round(int(m.group(1)) * 60 + float(m.group(2)), 3)])
            text += piece
        text = text.rstrip()
        if text.strip():
            out.append({"text": text, "ruby": [], "t": words[0][2] if words else None, "tr": None, "words": words})
    return out


def _word_durations(c) -> dict[int, int]:
    """Word start (ms) → duration (ms) from the raw NetEase YRC / Kugou KRC; the
    engine's word-level LRC keeps only the starts, karaoke wipes want the lengths."""
    import base64

    from krok_helper import lyrics as kl

    out: dict[int, int] = {}
    try:
        if c.provider_id == "ne":
            raw = kl._extract_nested_lyric(c.lyrics_payload, "yrc") or kl._extract_nested_lyric(c.lyrics_payload, "klyric")
            for line in raw.splitlines():
                m = kl._LINE_DURATION_PATTERN.match(line.strip())
                for w in kl._YRC_WORD_PATTERN.finditer(m.group(3) if m else ""):
                    out[int(w.group("start"))] = int(w.group("duration"))
        elif c.provider_id == "kg":
            content = str(((c.lyrics_payload or {}).get("download") or {}).get("content") or "")
            for line in kl._decrypt_kugou_krc(base64.b64decode(content)).splitlines():
                m = kl._LINE_DURATION_PATTERN.match(line.strip())
                for w in kl._KRC_WORD_PATTERN.finditer(m.group(3) if m else ""):
                    out[int(m.group(1)) + int(w.group("start"))] = int(w.group("duration"))
    except Exception:  # noqa: BLE001 - durations are a bonus
        return {}
    return out


def _add_durations(lines: list[dict], durs: dict[int, int]) -> None:
    """Append each word's length (seconds) as a 4th element when the raw source has it."""
    if not durs:
        return
    import bisect

    keys = sorted(durs)
    for line in lines:
        for w in line.get("words") or []:
            ms = int(round(w[2] * 1000))
            k = bisect.bisect_left(keys, ms)
            near = min((keys[j] for j in (k - 1, k) if 0 <= j < len(keys)), key=lambda x: abs(x - ms), default=None)
            if near is not None and abs(near - ms) <= 12 and len(w) == 3:
                w.append(round(durs[near] / 1000.0, 3))


def _attach_translation(lines: list[dict], translation_lrc: str) -> None:
    if not translation_lrc:
        return
    trans = parse_lrc_text(translation_lrc)
    by_time = {round(t["t"], 1): t["text"] for t in trans if t.get("t") is not None}
    for line in lines:
        if line.get("t") is None:
            continue
        hit = by_time.get(round(line["t"], 1))
        if hit and hit != line["text"] and not hit.startswith("//"):
            line["tr"] = hit


def _candidate_dict(c, idx: int) -> dict:
    from krok_helper.lyrics import LYRICS_PREVIEW_LINE, build_lyrics_preview

    from krok_helper.lyrics import LYRICS_PREVIEW_VERBATIM

    has_ruby = "[tool:utaten-ruby]" in (c.plain_lyrics or "")
    has_verbatim = bool((c.verbatim_lyrics or "").strip())
    if has_ruby:
        lines = parse_utaten_text(c.plain_lyrics)
    elif has_verbatim:  # word-level timing (NetEase YRC / Kugou KRC): keep every word's start
        lines = parse_verbatim_text(build_lyrics_preview(c, LYRICS_PREVIEW_VERBATIM).text)
        _add_durations(lines, _word_durations(c))
        _attach_translation(lines, c.translation_lyrics)
    else:
        try:
            text = build_lyrics_preview(c, LYRICS_PREVIEW_LINE).text
        except Exception:
            text = c.line_lyrics or c.plain_lyrics or ""
        lines = parse_lrc_text(text) if re.search(r"\[\d+:\d+", text) else [
            {"text": t.strip(), "ruby": [], "t": None, "tr": None} for t in text.splitlines() if t.strip()]
        _attach_translation(lines, c.translation_lyrics)
    return {
        "id": f"{c.provider_id}-{idx}",
        "provider": c.provider_id,
        "provider_name": c.provider_name,
        "title": c.title,
        "artist": c.artist,
        "album": c.album,
        "duration": c.duration_seconds,
        "url": c.source_url,
        "has_ruby": has_ruby,
        "has_timing": any(l.get("t") is not None for l in lines),
        "has_verbatim": any(l.get("words") for l in lines),
        "has_translation": any(l.get("tr") for l in lines),
        "line_count": len(lines),
        "lines": lines,
        "error": c.load_error or "",
    }


def _utaten_variants(queries: list[str]) -> list[str]:
    """UtaTen's search misses titles with decorations (``ALIVE～祈りの唄～``):
    also try the query without ～…～ / bracketed parts, then main title + artist."""
    out: list[str] = []
    for q in queries:
        plain = re.sub(r"[～~〜][^～~〜]*[～~〜]|[（(「『【\[].*?[）)」』】\]]", " ", q)
        plain = re.sub(r"\s+", " ", plain).strip()
        words = plain.split()
        for v in (q, plain, " ".join(words[:1] + words[-1:]) if len(words) > 2 else ""):
            if v and v not in out:
                out.append(v)
    return out


def search(queries: list[str], *, utaten_queries: list[str] | None = None, fetch_top: int = 5) -> list[dict]:
    """Search all providers. UtaTen (furigana) is queried separately as the
    workbench does; returns candidate dicts with parsed lines."""
    svc = _service()
    from krok_helper.lyrics import DEFAULT_LYRICS_PROVIDER_IDS

    found = []
    seen = set()

    def add(cands):
        for c in cands:
            key = (c.provider_id, c.track_id)
            if key in seen:
                continue
            seen.add(key)
            found.append(c)

    for q in _utaten_variants(utaten_queries or queries):
        try:
            add(svc.search(q, provider_ids=("utaten",), limit=3)[:2])
        except Exception:
            pass
        if any(c.provider_id == "utaten" for c in found):
            break
    for q in queries:
        try:
            batch = svc.search_batch(q, provider_ids=DEFAULT_LYRICS_PROVIDER_IDS, limit=12)
            add(batch.results[:fetch_top])
        except Exception:
            try:
                add(svc.search(q, limit=12)[:fetch_top])
            except Exception:
                pass
        if len(found) >= fetch_top + 1:
            break

    def load(c):
        try:
            return svc.fetch_lyrics(c)
        except Exception as exc:  # keep the candidate with its error
            c.load_error = str(exc)
            return c

    with ThreadPoolExecutor(max_workers=6) as pool:
        loaded = list(pool.map(load, found))
    out = []
    for idx, c in enumerate(loaded):
        try:
            d = _candidate_dict(c, idx)
        except Exception as exc:
            continue
        if d["line_count"] >= 4:
            out.append(d)
    out.sort(key=lambda d: (not d["has_ruby"], not d["has_timing"], -d["line_count"]))
    return out


# --------------------------------------------------------------- line utilities
def _norm(ch: str) -> str:
    return ch.lower()


def merge_ruby(target_lines: list[dict], ruby_lines: list[dict]) -> int:
    """Copy ruby spans from ``ruby_lines`` (e.g. UtaTen) onto ``target_lines``
    (e.g. synced LRC) by aligning the concatenated character streams.
    Returns the number of transferred spans."""
    src_chars, src_map = [], []
    src_spans = []
    for li, line in enumerate(ruby_lines):
        base = len(src_chars)
        for ci, ch in enumerate(line["text"]):
            if ch.isspace():
                continue
            src_map.append((li, ci))
            src_chars.append(_norm(ch))
        for s, e, r, *_ in line.get("ruby", []):
            src_spans.append((li, s, e, r))
    tgt_chars, tgt_map = [], []
    for li, line in enumerate(target_lines):
        for ci, ch in enumerate(line["text"]):
            if ch.isspace():
                continue
            tgt_map.append((li, ci))
            tgt_chars.append(_norm(ch))
    sm = difflib.SequenceMatcher(a=src_chars, b=tgt_chars, autojunk=False)
    pos_map: dict[tuple[int, int], tuple[int, int]] = {}
    for a, b, n in sm.get_matching_blocks():
        for k in range(n):
            pos_map[src_map[a + k]] = tgt_map[b + k]
    used: dict[int, list] = {}
    count = 0
    for li, s, e, r in src_spans:
        mapped = [pos_map.get((li, c)) for c in range(s, e + 1)]
        if any(m is None for m in mapped):
            continue
        tl = mapped[0][0]
        cols = [m[1] for m in mapped]
        if any(m[0] != tl for m in mapped) or cols != list(range(cols[0], cols[0] + len(cols))):
            continue
        used.setdefault(tl, []).append([cols[0], cols[-1], r])
        count += 1
    for tl, spans in used.items():
        target_lines[tl]["ruby"] = sorted(spans, key=lambda x: x[0])
    return count


def split_line(lines: list[dict], index: int, at: int) -> None:
    line = lines[index]
    text = line["text"]
    if not 0 < at < len(text):
        raise ValueError("拆分位置超出范围")
    left_text, right_text = text[:at].rstrip(), text[at:].lstrip()
    lshift = at + (len(text[at:]) - len(text[at:].lstrip()))
    words = line.get("words") or []
    # a word that crosses the split keeps its time on the side of its first character
    left = dict(line, text=left_text, ruby=[r for r in line.get("ruby", []) if r[1] < at],
                words=[[w[0], min(w[1], len(left_text) - 1), *w[2:]] for w in words if w[0] < len(left_text)])
    right_words = [[w[0] - lshift, w[1] - lshift, *w[2:]] for w in words if w[0] >= lshift]
    right = dict(line, text=right_text, t=right_words[0][2] if right_words else None, tr=None,
                 ruby=[[r[0] - lshift, r[1] - lshift, *r[2:]] for r in line.get("ruby", []) if r[0] >= at],
                 words=right_words)
    lines[index:index + 1] = [left, right]


def merge_lines(lines: list[dict], index: int, sep: str = " ") -> None:
    a, b = lines[index], lines[index + 1]
    shift = len(a["text"]) + len(sep)
    merged = dict(a, text=a["text"] + sep + b["text"],
                  ruby=list(a.get("ruby", [])) + [[r[0] + shift, r[1] + shift, *r[2:]] for r in b.get("ruby", [])],
                  words=list(a.get("words") or []) + [[w[0] + shift, w[1] + shift, *w[2:]] for w in b.get("words") or []])
    lines[index:index + 2] = [merged]


def auto_split_long(lines: list[dict], max_units: float = 17.0) -> int:
    """Split lines wider than ``max_units`` full-width characters at the space
    closest to the middle. Returns how many lines were split."""
    def width(s: str) -> float:
        return sum(0.5 if ord(c) < 0x2E80 else 1.0 for c in s)

    count = 0
    i = 0
    while i < len(lines):
        text = lines[i]["text"]
        if width(text) > max_units:
            spaces = [k for k, c in enumerate(text) if c in " 　" and 0 < k < len(text) - 1]
            if spaces:
                mid = len(text) / 2
                at = min(spaces, key=lambda k: abs(k - mid))
                # a phrase break (after , ; : ! ? 、 。) near the middle reads better than the exact middle
                phrase = [k for k in spaces if text[k - 1] in ",;:!?、。，" and abs(k - mid) <= len(text) * 0.22]
                if phrase:
                    at = min(phrase, key=lambda k: abs(k - mid))
                split_line(lines, i, at)
                count += 1
                continue
        i += 1
    return count


_CREDIT_LINE = re.compile(r"^\s*(作词|作詞|作曲|编曲|編曲|词|曲|制作人|製作|混音|母带|和声|吉他|贝斯|鼓|弦乐|录音|出品|"
                          r"演唱|Lyrics?|Lyricist|Composer|Compose[rd]?|Arrange[rd]?|Arrangement|Vocals?|Producer)"
                          r"\s*[:：]", re.I)


def is_lrc_text(text: str) -> bool:
    return len(re.findall(r"^\s*\[\d+:\d+(?:[.:]\d+)?\]", text, re.M)) >= 3


def parse_user_lrc(text: str) -> tuple[list[dict], list[str]]:
    """A user's .lrc file (often a NetEase / QQ export): timed lines plus the
    credits found in it. NetEase puts credits in JSON lines
    (``{"t":0,"c":[{"tx":"作词: "},{"tx":"…"}]}``) or as timed ``作词 : …`` lines
    before the first sung line; both are returned as ``credits``, not lyrics."""
    import json as _json

    credits: list[str] = []
    kept: list[str] = []
    for raw in text.splitlines():
        s = raw.strip()
        if s.startswith("{") and s.endswith("}"):
            try:
                obj = _json.loads(s)
                credits.append("".join(str(c.get("tx", "")) for c in obj.get("c", [])).strip())
                continue
            except (ValueError, AttributeError):
                pass
        kept.append(raw)
    lines = []
    for line in parse_lrc_text("\n".join(kept)):
        if not lines and _CREDIT_LINE.match(line["text"]):
            credits.append(line["text"])
            continue
        prev = lines[-1] if lines else None
        if prev and line["t"] is not None and prev["t"] is not None and round(line["t"], 1) == round(prev["t"], 1) \
                and line["text"] != prev["text"] and not re.search(r"[A-Za-z぀-ヿ]", line["text"]):
            # a bilingual export repeats the timestamp for the translation (no kana / Latin letters)
            if not prev.get("tr") and not line["text"].startswith("//"):
                prev["tr"] = line["text"]
            continue
        lines.append(line)
    return lines, [c for c in credits if c]


def parse_user_lyrics(text: str) -> list[dict]:
    """User pasted lyrics: supports ``漢字(かんじ)`` / ``漢字（かんじ）``,
    ``{漢字|かんじ}`` / ``{漢字||かんじ}`` ruby and a leading ``[歌手]`` or
    ``【歌手】`` singer tag."""
    out = []
    for raw in text.splitlines():
        raw = raw.strip()
        if not raw:
            continue
        singer = None
        m = re.match(r"^[\[【]([^\]】]{1,24})[\]】]\s*", raw)
        if m and not re.match(r"^\[\d", raw):
            singer = m.group(1)
            raw = raw[m.end():]
        raw = re.sub(r"\{([^{}|]+)\|\|?([^{}]*)\}", lambda mm: "{" + mm.group(1) + "||" + mm.group(2) + "}", raw)
        raw = re.sub(r"([㐀-鿿々〆ヶ]+)[(（]([぀-ヿー]+)[)）]",
                     lambda mm: "{" + mm.group(1) + "||" + mm.group(2) + "}", raw)
        parsed = parse_utaten_text(raw)
        if parsed:
            parsed[0]["singer_name"] = singer
            out.extend(parsed)
    return out
